Vagrant.configure("2") do |config| 
  config.vm.define :servidorGrafana do |servidorGrafana| 
    servidorGrafana.vm.box = "http-box" 
    servidorGrafana.vm.network "private_network", ip: "192.168.50.2"
    servidorGrafana.vm.network "forwarded_port", guest: 22, host: 2300, id: "ssh"
    servidorGrafana.vm.hostname = "servidorGrafana"
    servidorGrafana.vm.synced_folder './data', "/vagrant"
  end 
end
