Vagrant.configure("2") do |config| 
  config.vm.define :servidorMonitoreo do |servidorMonitoreo| 
    servidorMonitoreo.vm.box = "bento/ubuntu-22.04" 
    servidorMonitoreo.vm.network "private_network", ip: "192.168.50.2"
    servidorMonitoreo.vm.hostname = "servidorMonitoreo"
  end 
end 
